# Generated by Django 4.0.4 on 2022-05-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=233)),
                ('subtitle', models.CharField(max_length=233)),
                ('author', models.CharField(max_length=233)),
                ('isbn', models.CharField(max_length=233)),
            ],
        ),
    ]
